import Header from "../../components/Navbar/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div>
        <Header />
        {children}
      </div>
    </>
  );
}
