import { ChakraProvider } from "@chakra-ui/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ChakraProvider>
        <div>{children}</div>
      </ChakraProvider>
    </>
  );
}