import { ProfessionProvider } from "./context/professionalContext";
import { RecruiterProvider } from "../app/context/recruiterContext";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <RecruiterProvider>
          <ProfessionProvider>
            <>{children}</>
          </ProfessionProvider>
        </RecruiterProvider>
      </body>
    </html>
  );
}
